name: format, build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-solutions-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: fetch dependencies
      run: |
        sudo apt-get install clang-format clang-tidy

        wget -qO /tmp/llvm.sh https://apt.llvm.org/llvm.sh
        chmod +x /tmp/llvm.sh
        sudo /tmp/llvm.sh 20 all

        clang-20 --version

        pip3 install conan
        conan profile detect
    - name: clang format
      run : |
        script/format.sh
    - name: build
      run: |
        script/build.sh
    - name: clang tidy
      run : |
        script/tidy.sh
    - name: test
      run: |
        cd build/build/Release
        ./src/core/ngn-csv-test
        ./src/execution/ngn-exec-test
    - name: bench (dry-run)
      run: |
        cd build/build/Release
        ./src/execution/ngn-exec-bench --benchmark_dry_run
