name: format, build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-solutions-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: fetch dependencies
      run: |
        sudo apt-get install clang-format clang-tidy
    - name: clang format
      run : |
        find src/ -type f \( -name '*.c' -o -name '*.h' -o -name '*.cpp' -o -name '*.cc' \) -print0 | xargs -0 clang-format --dry-run -Werror
    - name: cmake
      run: |
        mkdir build
        cd build
        cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
    - name: make
      run: |
        cd build
        ninja
    - name: clang tidy
      run : |
        find src/ -type f \( -name '*.c' -o -name '*.h' -o -name '*.cpp' -o -name '*.cc' \) -print0 | xargs -0 clang-tidy -p build
    - name: test
      run: |
        cd build
        ./src/core/ngn-csv-test
