name: coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  coverage-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: fetch dependencies
        run: |
          wget -qO /tmp/llvm.sh https://apt.llvm.org/llvm.sh
          chmod +x /tmp/llvm.sh
          sudo /tmp/llvm.sh 20 all

          clang-20 --version
          llvm-profdata-20 --version
          llvm-cov-20 --version
      - name: build and run coverage
        run: |
          bash script/coverage.sh
      - name: upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: build-coverage/coverage-html
          if-no-files-found: error

